osx_image: xcode8
language: objective-c

cache: cocoapods
podfile: Podfile

before_install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
  - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet
  - pod update
  - pod install

script:
  - set -o pipefail
  - xcodebuild -workspace VSCAM.xcworkspace -scheme VSCAM -sdk iphonesimulator10.0 build analyze | xcpretty -c
  #- xcodebuild -workspace VSCAM.xcworkspace -scheme VSCAM -configuration Debug clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c
  #- xcodebuild -workspace VSCAM.xcworkspace -scheme VSCAM -configuration Release clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c

after_success:
  - sleep 5
